i12 resolved - change request id calc error
Northeastern-Electric-Racing/NER-PM-Dashboard pull request #36
Opened 2020-11-07 00:01 UTC by RahulR100

The function to increment the ID was broken when given numbers 0.008 and 0.009. This has been fixed by rounding the final result to 3 decimal places before converting to a string. Now 0.008 returns 0.009 instead of 0.0098888.... etc.

2020-11-07 00:19 UTC, jamescd18 requested changes
Quick fix. Also, JSDoc would be much appreciated on functions being edited. Thank you!

2020-11-07 00:19 UTC, jamescd18 commented on server-code/ChangeForm.js
> +        var nextNum = (parseFloat(numStr) + 0.001).toFixed(3).toString() // converts string to float and increments by 1
```suggestion
        var nextNum = (parseFloat(numStr) + 0.001).toFixed(3).toString(); // converts string to float and increments by 1
```

2020-11-08 18:50 UTC, RahulR100 commented on server-code/ChangeForm.js
> +        var nextNum = (parseFloat(numStr) + 0.001).toFixed(3).toString() // converts string to float and increments by 1
Oop.. always those semicolons ahaha

2020-11-13 18:32 UTC, jamescd18 requested changes
Looking pretty good! Just a couple minor edits, and the fix looks pretty good to me.

2020-11-13 18:32 UTC, jamescd18 commented on server-code/ChangeForm.js
> +* @return {void}
```suggestion
```

2020-11-13 18:32 UTC, jamescd18 commented on server-code/ChangeForm.js
> +* Pulls the new change request submitted to the form
```suggestion
* Pulls the new change request submitted to the form, formats the Change Request data, and adds it to the database spreadsheet of all Change Requests. 
```

2020-11-13 18:33 UTC, jamescd18 approved these changes
Positively lovely.

2020-11-13 18:34 UTC, merged