i43–create new page called dashboard
Northeastern-Electric-Racing/NER-PM-Dashboard pull request #52
Opened 2020-12-22 22:29 UTC by eshwaribhide

–Created new Dashboard.html page in page-content, same form/dropdown thing as Reports with 2 options for status dashboard/upcoming deadlines. Got rid of those options in Reports
–Created server-side Dashboard.js file, simply taking existing functionality for status dashboard/upcoming deadlines in Reports and moving it there
–Created client-side Dashboard functionality

2020-12-22 22:43 UTC, eshwaribhide commented
So one thing is, I used the words "feature type" instead of "dashboard type" because I don't think that dashboard type makes sense as a reference to "upcoming deadlines". I understood that status dashboard & upcoming deadlines were two features, that is why I use feature/feature type. Please suggest a different name, if you think that one isn't the best.

2020-12-23 18:43 UTC, kevinyu328 requested changes
Really nice work! Just some small edits

2020-12-23 18:43 UTC, kevinyu328 commented on client-code/JavaScript.html
> +        runnerHTML.withUserObject($("#dashboard-content")).getPlaceholderHTML("* Coming Soon * <br> Choose Dashboard Type Above");
```suggestion
        runnerHTML.withUserObject($("#dashboard-content")).getPlaceholderHTML("Choose Dashboard Type Above");

```

2020-12-23 18:43 UTC, kevinyu328 commented on page-content/Index.html
> +        <div class="container-lg page" id="dashboard">
```suggestion
        <div class="container-lg page" id="page-dashboard">

```

2020-12-23 18:43 UTC, kevinyu328 commented on server-code/Dashboard.js
> + * @return {String}
```suggestion
 * @param {String} dashboardType - The type of dashboard to be displayed.
 * @return {String} HTML formatted content for the selected dashboard type.
```

2020-12-23 19:03 UTC, kevinyu328 commented on client-code/JavaScript.html
> +    *
```suggestion
    * 
    * @return {void}

```

2020-12-23 20:54 UTC, kevinyu328 approved these changes
Looks good!

2020-12-23 20:54 UTC, merged